# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_control.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'order_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order_control.proto\x12\rorder_control\"<\n\x16ItemRequestCreateOrder\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"=\n\x17ItemResponseCreateOrder\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x05\"N\n\x12RequestCreateOrder\x12\x38\n\titem_list\x18\x01 \x03(\x0b\x32%.order_control.ItemRequestCreateOrder\"P\n\x13ResponseCreateOrder\x12\x39\n\titem_list\x18\x01 \x03(\x0b\x32&.order_control.ItemResponseCreateOrder\"&\n\x12RequestCancelOrder\x12\x10\n\x08order_id\x18\x01 \x01(\x05\"%\n\x13ResponseCancelOrder\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x18\n\x16RequestFinishExecution\"\\\n\x17ResponseFinishExecution\x12\x1e\n\x16stock_control_response\x18\x01 \x01(\x05\x12!\n\x19number_of_existing_orders\x18\x02 \x01(\x05\x32\xa5\x02\n\x0cOrderControl\x12W\n\x0c\x63reate_order\x12!.order_control.RequestCreateOrder\x1a\".order_control.ResponseCreateOrder\"\x00\x12W\n\x0c\x63\x61ncel_order\x12!.order_control.RequestCancelOrder\x1a\".order_control.ResponseCancelOrder\"\x00\x12\x63\n\x10\x66inish_execution\x12%.order_control.RequestFinishExecution\x1a&.order_control.ResponseFinishExecution\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMREQUESTCREATEORDER']._serialized_start=38
  _globals['_ITEMREQUESTCREATEORDER']._serialized_end=98
  _globals['_ITEMRESPONSECREATEORDER']._serialized_start=100
  _globals['_ITEMRESPONSECREATEORDER']._serialized_end=161
  _globals['_REQUESTCREATEORDER']._serialized_start=163
  _globals['_REQUESTCREATEORDER']._serialized_end=241
  _globals['_RESPONSECREATEORDER']._serialized_start=243
  _globals['_RESPONSECREATEORDER']._serialized_end=323
  _globals['_REQUESTCANCELORDER']._serialized_start=325
  _globals['_REQUESTCANCELORDER']._serialized_end=363
  _globals['_RESPONSECANCELORDER']._serialized_start=365
  _globals['_RESPONSECANCELORDER']._serialized_end=402
  _globals['_REQUESTFINISHEXECUTION']._serialized_start=404
  _globals['_REQUESTFINISHEXECUTION']._serialized_end=428
  _globals['_RESPONSEFINISHEXECUTION']._serialized_start=430
  _globals['_RESPONSEFINISHEXECUTION']._serialized_end=522
  _globals['_ORDERCONTROL']._serialized_start=525
  _globals['_ORDERCONTROL']._serialized_end=818
# @@protoc_insertion_point(module_scope)
