# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stock_control.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'stock_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13stock_control.proto\x12\rstock_control\"8\n\x11RequestAddProduct\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"(\n\x12ResponseAddProduct\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"@\n\x1aRequestChangeProductAmount\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"-\n\x1bResponseChangeProductAmount\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x15\n\x13RequestListProducts\":\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\"@\n\x14ResponseListProducts\x12(\n\x08products\x18\x01 \x03(\x0b\x32\x16.stock_control.Product\"\x18\n\x16RequestFinishExecution\">\n\x17ResponseFinishExecution\x12#\n\x1bnumber_of_existing_products\x18\x01 \x01(\x05\x32\x97\x03\n\x0cStockControl\x12T\n\x0b\x61\x64\x64_product\x12 .stock_control.RequestAddProduct\x1a!.stock_control.ResponseAddProduct\"\x00\x12p\n\x15\x63hange_product_amount\x12).stock_control.RequestChangeProductAmount\x1a*.stock_control.ResponseChangeProductAmount\"\x00\x12Z\n\rlist_products\x12\".stock_control.RequestListProducts\x1a#.stock_control.ResponseListProducts\"\x00\x12\x63\n\x10\x66inish_execution\x12%.stock_control.RequestFinishExecution\x1a&.stock_control.ResponseFinishExecution\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTADDPRODUCT']._serialized_start=38
  _globals['_REQUESTADDPRODUCT']._serialized_end=94
  _globals['_RESPONSEADDPRODUCT']._serialized_start=96
  _globals['_RESPONSEADDPRODUCT']._serialized_end=136
  _globals['_REQUESTCHANGEPRODUCTAMOUNT']._serialized_start=138
  _globals['_REQUESTCHANGEPRODUCTAMOUNT']._serialized_end=202
  _globals['_RESPONSECHANGEPRODUCTAMOUNT']._serialized_start=204
  _globals['_RESPONSECHANGEPRODUCTAMOUNT']._serialized_end=249
  _globals['_REQUESTLISTPRODUCTS']._serialized_start=251
  _globals['_REQUESTLISTPRODUCTS']._serialized_end=272
  _globals['_PRODUCT']._serialized_start=274
  _globals['_PRODUCT']._serialized_end=332
  _globals['_RESPONSELISTPRODUCTS']._serialized_start=334
  _globals['_RESPONSELISTPRODUCTS']._serialized_end=398
  _globals['_REQUESTFINISHEXECUTION']._serialized_start=400
  _globals['_REQUESTFINISHEXECUTION']._serialized_end=424
  _globals['_RESPONSEFINISHEXECUTION']._serialized_start=426
  _globals['_RESPONSEFINISHEXECUTION']._serialized_end=488
  _globals['_STOCKCONTROL']._serialized_start=491
  _globals['_STOCKCONTROL']._serialized_end=898
# @@protoc_insertion_point(module_scope)
